spring.application.name=ev-charging-system
spring.datasource.url=jdbc:mysql://localhost:3306/ev_charging_db
spring.datasource.username=root
spring.datasource.password=MyNewPassword123!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true